"""Pre-consultation questionnaire templates for diabetes care.

Each template is a dict with:
  - category: str — human-readable label for the template
  - questions: list[dict] — ordered questions with optional conditional logic

Question schema:
  - question_id: str — unique identifier within the template
  - question_text: str — display text (Chinese)
  - answer_type: "text" | "select" | "number" | "boolean"
  - options: list[str] | None — choices for select type
  - required: bool — whether the question must be answered
  - depends_on: dict | None — conditional display, e.g.
      {"question_id": "chief_complaint", "matches": "多尿多饮多食"}
"""

_QUESTIONS_NEW_DIABETES = [
    {
        "question_id": "chief_complaint",
        "question_text": "您最近有哪些不适症状？",
        "answer_type": "select",
        "options": [
            "多尿、多饮、多食、体重下降",
            "疲乏无力",
            "视力模糊",
            "皮肤瘙痒或感染",
            "伤口愈合缓慢",
            "无明显症状（体检发现）",
            "其他",
        ],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "symptom_duration",
        "question_text": "上述症状持续了多长时间？",
        "answer_type": "select",
        "options": ["1周以内", "1-4周", "1-3个月", "3-6个月", "6个月以上"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "discovery_method",
        "question_text": "您是如何发现血糖升高的？",
        "answer_type": "select",
        "options": ["日常体检", "因不适就医", "自行测量", "其他科室就诊时发现"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "recent_weight_change",
        "question_text": "近半年体重有无明显变化？",
        "answer_type": "select",
        "options": ["无明显变化", "体重下降超过5kg", "体重增加超过5kg"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "diet_habit",
        "question_text": "您的饮食偏好如何？",
        "answer_type": "select",
        "options": ["偏甜食/含糖饮料", "偏油腻/高脂", "偏咸/重口味", "饮食较清淡均衡", "不规律"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "exercise_frequency",
        "question_text": "您平时运动频率如何？",
        "answer_type": "select",
        "options": ["几乎不运动", "每周1-2次", "每周3-4次", "每周5次以上"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "family_diabetes",
        "question_text": "直系亲属（父母、兄弟姐妹、子女）中是否有糖尿病患者？",
        "answer_type": "select",
        "options": ["有", "没有", "不清楚"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "previous_diagnosis",
        "question_text": "此前是否被诊断过糖尿病或血糖异常？",
        "answer_type": "select",
        "options": ["未诊断过", "诊断过糖尿病前期", "诊断过妊娠糖尿病", "其他相关诊断"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "other_conditions",
        "question_text": "您是否患有其他慢性疾病？",
        "answer_type": "select",
        "options": ["高血压", "高血脂", "冠心病", "脑血管疾病", "肾脏疾病", "甲状腺疾病", "无", "其他"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "current_medications",
        "question_text": "目前是否在服用其他药物？",
        "answer_type": "text",
        "options": None,
        "required": False,
        "depends_on": None,
    },
]

_QUESTIONS_FOLLOW_UP_ROUTINE = [
    {
        "question_id": "chief_complaint",
        "question_text": "本次复诊您最关注什么问题？",
        "answer_type": "select",
        "options": ["血糖控制情况", "药物调整", "饮食运动指导", "常规复查", "身体不适"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "glucose_self_monitoring",
        "question_text": "近期自我血糖监测频率如何？",
        "answer_type": "select",
        "options": ["每天监测", "每周3-5次", "每周1-2次", "基本不测"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "fasting_glucose_range",
        "question_text": "近期空腹血糖一般在什么范围（mmol/L）？",
        "answer_type": "select",
        "options": ["4.4-7.0", "7.1-10.0", "10.1-15.0", "15以上", "未测/不清楚"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "postprandial_glucose_range",
        "question_text": "近期餐后2小时血糖一般在什么范围（mmol/L）？",
        "answer_type": "select",
        "options": ["<7.8", "7.8-10.0", "10.1-13.9", "14以上", "未测/不清楚"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "medication_adherence",
        "question_text": "您按时服药的依从性如何？",
        "answer_type": "select",
        "options": ["严格按时服药", "偶尔漏服（每周1-2次）", "经常漏服（每周3次以上）", "自行调整过用药"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "medication_side_effects",
        "question_text": "服药后有无不适反应？",
        "answer_type": "select",
        "options": ["无不适", "有胃肠道不适", "有头晕乏力", "有低血糖反应", "其他不适"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "hypoglycemia_episodes",
        "question_text": "近1月内有无低血糖事件（血糖<3.9mmol/L）？",
        "answer_type": "select",
        "options": ["无", "1-2次", "3-5次", "5次以上"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "hypoglycemia_detail",
        "question_text": "请描述低血糖发生的时间、症状和处理情况：",
        "answer_type": "text",
        "options": None,
        "required": False,
        "depends_on": {"question_id": "hypoglycemia_episodes", "matches_any": ["1-2次", "3-5次", "5次以上"]},
    },
    {
        "question_id": "diet_adherence",
        "question_text": "近期饮食控制情况如何？",
        "answer_type": "select",
        "options": ["严格遵守饮食方案", "基本遵守，偶尔放松", "控制较差", "不清楚该怎么吃"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "exercise_adherence",
        "question_text": "近期运动情况如何？",
        "answer_type": "select",
        "options": ["规律运动（每周≥150分钟）", "偶有运动", "基本不运动"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "weight_trend",
        "question_text": "近3个月体重变化趋势？",
        "answer_type": "select",
        "options": ["稳定", "上升", "下降"],
        "required": False,
        "depends_on": None,
    },
]

_QUESTIONS_FOLLOW_UP_POOR_CONTROL = [
    {
        "question_id": "chief_complaint",
        "question_text": "您认为血糖控制不佳的主要原因是什么？",
        "answer_type": "select",
        "options": [
            "药物方案不合理",
            "饮食控制困难",
            "缺乏运动",
            "经常忘记服药",
            "近期压力大/睡眠差",
            "有并发感染或疾病",
            "不知道原因",
        ],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "glucose_fluctuation",
        "question_text": "近期血糖波动情况如何？",
        "answer_type": "select",
        "options": ["持续偏高", "忽高忽低", "早晨空腹高", "餐后高", "夜间低血糖/清晨反跳高"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "highest_glucose",
        "question_text": "近期测得最高血糖值是多少（mmol/L）？",
        "answer_type": "number",
        "options": None,
        "required": False,
        "depends_on": None,
    },
    {
        "question_id": "lowest_glucose",
        "question_text": "近期测得最低血糖值是多少（mmol/L）？",
        "answer_type": "number",
        "options": None,
        "required": False,
        "depends_on": None,
    },
    {
        "question_id": "meal_pattern",
        "question_text": "您每天的进餐规律如何？",
        "answer_type": "select",
        "options": ["三餐规律", "经常不吃早餐", "晚餐吃得晚或量大", "有吃夜宵习惯", "进餐时间不固定"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "staple_food_amount",
        "question_text": "您每餐主食（米饭/面食等）大约吃多少？",
        "answer_type": "select",
        "options": ["少于1两（50g）", "1-2两（50-100g）", "2-3两（100-150g）", "3两以上（>150g）", "不确定"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "sugary_drinks",
        "question_text": "是否饮用含糖饮料或果汁？",
        "answer_type": "select",
        "options": ["从不", "偶尔（每周1-2次）", "经常（每周3次以上）", "每天"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "alcohol_use",
        "question_text": "饮酒情况如何？",
        "answer_type": "select",
        "options": ["不饮酒", "偶尔少量", "经常饮酒", "每天饮酒"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "sleep_quality",
        "question_text": "近期睡眠质量如何？",
        "answer_type": "select",
        "options": ["良好", "一般", "较差（入睡困难/早醒/多梦）", "很差"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "stress_level",
        "question_text": "近期精神压力或情绪状态如何？",
        "answer_type": "select",
        "options": ["无明显压力", "轻度压力/焦虑", "中度压力/焦虑", "重度压力/焦虑"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "medication_barrier",
        "question_text": "在用药方面有什么困难吗？",
        "answer_type": "select",
        "options": ["无困难", "忘记服药", "担心副作用", "经济负担", "注射恐惧", "不方便携带"],
        "required": True,
        "depends_on": None,
    },
]

_QUESTIONS_COMPLICATION_SCREENING = [
    {
        "question_id": "chief_complaint",
        "question_text": "本次筛查您最担心的并发症是？",
        "answer_type": "select",
        "options": ["眼部病变", "肾脏病变", "神经病变", "心血管病变", "足部病变", "全面筛查", "医生建议"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "vision_changes",
        "question_text": "近期有无视力变化？",
        "answer_type": "select",
        "options": ["无变化", "视物模糊", "眼前飞蚊感", "视野缺损", "已确诊视网膜病变"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "last_eye_exam",
        "question_text": "上一次眼底检查是什么时候？",
        "answer_type": "select",
        "options": ["半年内", "1年内", "1-2年", "2年以上", "从未检查"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "edema",
        "question_text": "近期有无眼睑或下肢水肿？",
        "answer_type": "select",
        "options": ["无", "偶尔轻微", "经常", "持续明显"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "urine_foam",
        "question_text": "排尿时有无泡沫增多？",
        "answer_type": "select",
        "options": ["无", "偶尔", "经常"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "numbness",
        "question_text": "有无手脚麻木、刺痛或烧灼感？",
        "answer_type": "select",
        "options": ["无", "偶尔有", "经常有（不影响日常）", "严重影响日常活动"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "foot_check",
        "question_text": "您是否经常检查双脚（有无破损、水泡、颜色变化）？",
        "answer_type": "select",
        "options": ["每天检查", "偶尔检查", "从不检查", "不知道需要检查"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "foot_issues",
        "question_text": "双脚有无以下问题？",
        "answer_type": "select",
        "options": ["无问题", "足癣/真菌感染", "皮肤干裂", "鸡眼/胼胝", "伤口愈合不良", "足部变形"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "chest_pain",
        "question_text": "近期有无胸闷、胸痛或心悸？",
        "answer_type": "select",
        "options": ["无", "偶尔有", "经常有"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "blood_pressure_control",
        "question_text": "近期血压控制情况如何？",
        "answer_type": "select",
        "options": ["正常（<130/80）", "偏高（130-139/80-89）", "高（>140/90）", "未测/不清楚"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "lipid_control",
        "question_text": "近期血脂检查结果如何？",
        "answer_type": "select",
        "options": ["正常", "偏高", "未查/不清楚"],
        "required": True,
        "depends_on": None,
    },
]

_QUESTIONS_ANNUAL_REVIEW = [
    {
        "question_id": "chief_complaint",
        "question_text": "过去一年，您对自己糖尿病的整体管理满意吗？",
        "answer_type": "select",
        "options": ["满意", "基本满意", "不太满意", "很不满意"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "hba1c_awareness",
        "question_text": "您是否知道最近一次糖化血红蛋白（HbA1c）的结果？",
        "answer_type": "select",
        "options": ["知道（约6%以下）", "知道（约6-7%）", "知道（约7-8%）", "知道（约8%以上）", "不清楚"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "annual_eye_exam",
        "question_text": "过去一年是否完成年度眼底检查？",
        "answer_type": "boolean",
        "options": None,
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "annual_kidney_check",
        "question_text": "过去一年是否检测过尿微量白蛋白/肾功能？",
        "answer_type": "boolean",
        "options": None,
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "annual_foot_exam",
        "question_text": "过去一年是否做过专业足部检查？",
        "answer_type": "boolean",
        "options": None,
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "annual_lipid_check",
        "question_text": "过去一年是否检测过血脂？",
        "answer_type": "boolean",
        "options": None,
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "medication_adjustment",
        "question_text": "过去一年药物方案是否有过调整？",
        "answer_type": "select",
        "options": ["未调整", "调整过1次", "调整过2-3次", "调整过3次以上"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "hospitalization",
        "question_text": "过去一年有无因糖尿病相关原因住院或急诊？",
        "answer_type": "select",
        "options": ["无", "1次", "2次", "3次及以上"],
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "lifestyle_change",
        "question_text": "过去一年在饮食和运动方面有没有做出有益的改变？",
        "answer_type": "text",
        "options": None,
        "required": False,
        "depends_on": None,
    },
    {
        "question_id": "management_goals",
        "question_text": "未来一年您在糖尿病管理方面最想实现的目标是什么？",
        "answer_type": "text",
        "options": None,
        "required": False,
        "depends_on": None,
    },
    {
        "question_id": "immunization",
        "question_text": "过去一年是否接种过流感疫苗？",
        "answer_type": "boolean",
        "options": None,
        "required": True,
        "depends_on": None,
    },
    {
        "question_id": "mental_health",
        "question_text": "糖尿病对您的心理和情绪影响如何？",
        "answer_type": "select",
        "options": ["无影响", "偶尔焦虑/担忧", "经常感到压力", "有明显的抑郁情绪"],
        "required": True,
        "depends_on": None,
    },
]

TEMPLATES = {
    "new_diabetes": {
        "category": "新诊断糖尿病初诊",
        "questions": _QUESTIONS_NEW_DIABETES,
    },
    "follow_up_routine": {
        "category": "常规复诊",
        "questions": _QUESTIONS_FOLLOW_UP_ROUTINE,
    },
    "follow_up_poor_control": {
        "category": "血糖控制不佳复诊",
        "questions": _QUESTIONS_FOLLOW_UP_POOR_CONTROL,
    },
    "complication_screening": {
        "category": "并发症筛查",
        "questions": _QUESTIONS_COMPLICATION_SCREENING,
    },
    "annual_review": {
        "category": "年度综合评估",
        "questions": _QUESTIONS_ANNUAL_REVIEW,
    },
}


def get_template(template_id: str) -> dict | None:
    """Return a template by its ID, or None if not found."""
    return TEMPLATES.get(template_id)
