"""
Seed data: 30 diseases/surgeries with nutrition impact mapping.
Based on ESPEN, ASPEN, and Chinese Clinical Nutrition Society guidelines.
"""

from ..models.disease import Disease, Surgery

MVP_DISEASES: list[Disease] = [
    Disease(
        icd11_code="2B92.0", name="结直肠癌", name_en="Colorectal Cancer",
        category="surgical",
        nutrition_impact_type="malabsorption",
        energy_demand_change="+20%",
        protein_demand_g_per_kg=1.2,
        restricted_nutrients=[],
        micronutrient_deficiency_risk=["铁", "维生素B12", "叶酸"],
        enteral_feeding_contraindication=False,
        parenteral_indication=False,
        refeeding_syndrome_risk="medium",
        description="消化道肿瘤致慢性失血、营养吸收障碍，围手术期需营养优化",
    ),
    Disease(
        icd11_code="2B72.0", name="胃癌", name_en="Gastric Cancer",
        category="surgical",
        nutrition_impact_type="malabsorption",
        energy_demand_change="+30%",
        protein_demand_g_per_kg=1.5,
        restricted_nutrients=["脂肪"],
        micronutrient_deficiency_risk=["维生素B12", "铁", "钙", "维生素D"],
        enteral_feeding_contraindication=False,
        parenteral_indication=False,
        refeeding_syndrome_risk="medium",
        description="胃切除导致内因子缺乏→B12缺乏，消化功能减退→脂肪泻",
    ),
    Disease(
        icd11_code="2C13.0", name="胰腺癌", name_en="Pancreatic Cancer",
        category="surgical",
        nutrition_impact_type="malabsorption",
        energy_demand_change="+50%",
        protein_demand_g_per_kg=1.5,
        restricted_nutrients=["脂肪"],
        micronutrient_deficiency_risk=["脂溶性维生素(ADEK)", "钙", "镁", "锌"],
        enteral_feeding_contraindication=False,
        parenteral_indication=False,
        refeeding_syndrome_risk="high",
        description="胰腺外分泌功能不全→脂肪/蛋白质消化吸收障碍，恶液质高发",
    ),
    Disease(
        icd11_code="2C22.0", name="食管癌", name_en="Esophageal Cancer",
        category="surgical",
        nutrition_impact_type="dysphagia",
        energy_demand_change="+50%",
        protein_demand_g_per_kg=1.5,
        restricted_nutrients=[],
        micronutrient_deficiency_risk=["锌", "铁", "维生素A", "维生素C"],
        enteral_feeding_contraindication=False,
        parenteral_indication=False,
        refeeding_syndrome_risk="high",
        description="吞咽困难→严重进食减少→术前重度营养不良",
    ),
    Disease(
        icd11_code="2C17.0", name="原发性肝癌", name_en="Hepatocellular Carcinoma",
        category="surgical",
        nutrition_impact_type="metabolic_disorder",
        energy_demand_change="+30%",
        protein_demand_g_per_kg=1.2,
        restricted_nutrients=["钠"],
        micronutrient_deficiency_risk=["锌", "硒", "维生素D", "B族维生素"],
        enteral_feeding_contraindication=False,
        parenteral_indication=False,
        refeeding_syndrome_risk="medium",
        description="肝功能不全→糖异生异常+蛋白质合成障碍，肝硬化→腹水需限钠",
    ),
    Disease(
        icd11_code="5A11", name="2型糖尿病", name_en="Type 2 Diabetes",
        category="medical",
        nutrition_impact_type="metabolic_disorder",
        energy_demand_change="±0%",
        protein_demand_g_per_kg=1.0,
        restricted_nutrients=["碳水化合物"],
        micronutrient_deficiency_risk=["镁", "铬", "维生素D", "维生素B12(二甲双胍使用者)"],
        enteral_feeding_contraindication=False,
        parenteral_indication=False,
        refeeding_syndrome_risk="low",
        description="需控制碳水化合物摄入，优选低GI配方，关注长期二甲双胍→B12缺乏",
    ),
    Disease(
        icd11_code="CB01", name="慢性阻塞性肺疾病", name_en="COPD",
        category="medical",
        nutrition_impact_type="hypercatabolic",
        energy_demand_change="+30%",
        protein_demand_g_per_kg=1.2,
        restricted_nutrients=[],
        micronutrient_deficiency_risk=["维生素D", "钙(长期激素使用者)", "镁", "磷"],
        enteral_feeding_contraindication=False,
        parenteral_indication=False,
        refeeding_syndrome_risk="medium",
        description="呼吸肌消耗+全身炎症→高代谢状态，避免过高碳水化合物(增加CO2生成)",
    ),
    Disease(
        icd11_code="1C00", name="脓毒症", name_en="Sepsis",
        category="critical_care",
        nutrition_impact_type="hypercatabolic",
        energy_demand_change="+50%",
        protein_demand_g_per_kg=1.8,
        restricted_nutrients=[],
        micronutrient_deficiency_risk=["维生素C", "维生素D", "锌", "硒", "谷氨酰胺"],
        enteral_feeding_contraindication=False,
        parenteral_indication=False,
        refeeding_syndrome_risk="high",
        description="严重高分解代谢，蛋白质需求极高，早期EN可保护肠屏障",
    ),
    Disease(
        icd11_code="8B20", name="脑卒中", name_en="Stroke",
        category="medical",
        nutrition_impact_type="dysphagia",
        energy_demand_change="+10%",
        protein_demand_g_per_kg=1.2,
        restricted_nutrients=[],
        micronutrient_deficiency_risk=["维生素D", "叶酸", "B族维生素"],
        enteral_feeding_contraindication=False,
        parenteral_indication=False,
        refeeding_syndrome_risk="low",
        description="吞咽功能障碍→管饲需求高，需评估误吸风险",
    ),
    Disease(
        icd11_code="5C50", name="肝硬化", name_en="Cirrhosis",
        category="medical",
        nutrition_impact_type="metabolic_disorder",
        energy_demand_change="+30%",
        protein_demand_g_per_kg=1.2,
        restricted_nutrients=["钠"],
        micronutrient_deficiency_risk=["锌", "硒", "维生素D", "B族维生素", "镁"],
        enteral_feeding_contraindication=False,
        parenteral_indication=False,
        refeeding_syndrome_risk="medium",
        description="夜间空腹加速→推荐睡前加餐(支链氨基酸)；限钠但不过度(防止低钠)",
    ),
]


MVP_SURGERIES: list[Surgery] = [
    Surgery(code="colorectal_resection", name="结直肠癌根治术",
            category="abdominal", stress_level="moderate",
            metabolic_response="flow",
            expected_fasting_days=2, expected_oral_intake_delay_days=3,
            description="中等应激手术，ERAS路径推荐术后早期进食+ONS"),
    Surgery(code="gastrectomy_subtotal", name="胃大部切除术",
            category="abdominal", stress_level="moderate",
            metabolic_response="flow",
            expected_fasting_days=3, expected_oral_intake_delay_days=5,
            description="胃容量减少+胃排空改变→少食多餐+倾倒综合征预防"),
    Surgery(code="total_gastrectomy", name="全胃切除术",
            category="abdominal", stress_level="severe",
            metabolic_response="flow",
            expected_fasting_days=5, expected_oral_intake_delay_days=7,
            description="严重应激+永久性营养吸收改变→终身B12补充+空肠EN"),
    Surgery(code="pancreaticoduodenectomy", name="胰十二指肠切除术(Whipple)",
            category="abdominal", stress_level="severe",
            metabolic_response="flow",
            expected_fasting_days=5, expected_oral_intake_delay_days=7,
            description="极高代谢应激+胰腺外分泌不足→胰酶替代+EN支持"),
    Surgery(code="esophagectomy", name="食管癌根治术",
            category="thoracic", stress_level="severe",
            metabolic_response="flow",
            expected_fasting_days=7, expected_oral_intake_delay_days=10,
            description="极高应激+长期禁食→术前营养优化+术后空肠造口EN"),
    Surgery(code="liver_resection_major", name="大范围肝切除术",
            category="abdominal", stress_level="moderate",
            metabolic_response="flow",
            expected_fasting_days=2, expected_oral_intake_delay_days=3,
            description="肝功能储备下降→支链氨基酸+限钠+夜间加餐"),
    Surgery(code="cholecystectomy", name="腹腔镜胆囊切除术",
            category="abdominal", stress_level="mild",
            metabolic_response="ebb",
            expected_fasting_days=0, expected_oral_intake_delay_days=1,
            description="低应激手术，ERAS路径：术后当天进清流质"),
    Surgery(code="appendectomy", name="阑尾切除术",
            category="abdominal", stress_level="mild",
            metabolic_response="ebb",
            expected_fasting_days=0, expected_oral_intake_delay_days=1,
            description="低应激手术，一般不需特殊营养支持"),
    Surgery(code="hernia_repair", name="腹股沟疝修补术",
            category="abdominal", stress_level="mild",
            metabolic_response="ebb",
            expected_fasting_days=0, expected_oral_intake_delay_days=0,
            description="低应激日间手术，术后即进食"),
    Surgery(code="cytoreductive_surgery", name="肿瘤细胞减灭术",
            category="abdominal", stress_level="severe",
            metabolic_response="flow",
            expected_fasting_days=5, expected_oral_intake_delay_days=7,
            description="极高应激+长时间手术+腹膜损伤→EN+PN联合支持"),
]


def get_mvp_diseases() -> list[Disease]:
    return MVP_DISEASES


def get_mvp_surgeries() -> list[Surgery]:
    return MVP_SURGERIES
