"""
Seed data: 50 FSMP products (based on real NMPA-registered products).
All registration numbers are illustrative — replace with real NMPA data in production.

Categories:
- complete (全营养): 20 products
- specific_complete (特定全营养): 18 products
- incomplete (非全营养): 7 products
- modular (组件): 5 products
"""

from ..models.fsmp_product import FSMPProduct

MVP_FSMP_PRODUCTS: list[FSMPProduct] = [
    # ============ 全营养配方 (Complete) ============
    FSMPProduct(
        nmpa_registration_no="TY20220001", brand_name="能全力(Nutrison)",
        manufacturer="Nutricia (纽迪希亚)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=1.5, osmolarity_mOsm_L=250,
        special_features=["fiber_enriched"],
        price_per_unit_yuan=85, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220002", brand_name="能全力高能(Nutrison Energy)",
        manufacturer="Nutricia (纽迪希亚)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=150,
        protein_source="casein", protein_content_g_per_100ml=6.0,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=1.5, osmolarity_mOsm_L=320,
        special_features=["fiber_enriched"],
        price_per_unit_yuan=95, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220003", brand_name="能全力蛋白质强化(Nutrison Protein Plus)",
        manufacturer="Nutricia (纽迪希亚)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=125,
        protein_source="casein", protein_content_g_per_100ml=6.3,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=1.2, osmolarity_mOsm_L=300,
        special_features=["fiber_enriched"],
        price_per_unit_yuan=90, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220004", brand_name="能全素(Nutrison Soya)",
        manufacturer="Nutricia (纽迪希亚)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="soy", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精+葡萄糖浆", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=240,
        special_features=[],
        price_per_unit_yuan=75, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220005", brand_name="安素(Ensure)",
        manufacturer="Abbott (雅培)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein+whey", protein_content_g_per_100ml=3.8,
        carb_source="麦芽糊精+蔗糖", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=300,
        special_features=[],
        price_per_unit_yuan=70, unit_size_ml=400,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220006", brand_name="安素高蛋白(Ensure Plus)",
        manufacturer="Abbott (雅培)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=150,
        protein_source="casein+whey", protein_content_g_per_100ml=6.0,
        carb_source="麦芽糊精+蔗糖", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=450,
        special_features=[],
        price_per_unit_yuan=85, unit_size_ml=220,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220007", brand_name="瑞能(Supportan)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精", fat_source="fish_oil",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=290,
        special_features=["immune_modulation"],
        price_per_unit_yuan=120, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220008", brand_name="瑞素(Fresubin)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein", protein_content_g_per_100ml=3.8,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=250,
        special_features=[],
        price_per_unit_yuan=75, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220009", brand_name="瑞代(Fresubin Energy)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=150,
        protein_source="casein", protein_content_g_per_100ml=5.6,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=380,
        special_features=[],
        price_per_unit_yuan=85, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220010", brand_name="瑞先(Fresubin Fibre)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein", protein_content_g_per_100ml=3.8,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=2.0, osmolarity_mOsm_L=250,
        special_features=["fiber_enriched"],
        price_per_unit_yuan=80, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220011", brand_name="力存(Enteral Nutrition)",
        manufacturer="华瑞制药(SSPC)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=260,
        special_features=[],
        price_per_unit_yuan=65, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220012", brand_name="力存纤维(Enteral Fibre)",
        manufacturer="华瑞制药(SSPC)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=1.5, osmolarity_mOsm_L=250,
        special_features=["fiber_enriched"],
        price_per_unit_yuan=70, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220013", brand_name="伊力佳(Impact)",
        manufacturer="Nestle (雀巢健康科学)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein+whey", protein_content_g_per_100ml=5.6,
        carb_source="麦芽糊精", fat_source="fish_oil",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=310,
        special_features=["immune_modulation"],
        price_per_unit_yuan=140, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220014", brand_name="百普力(Peptamen)",
        manufacturer="Nestle (雀巢健康科学)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="hydrolysate", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精", fat_source="MCT+LCT",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=290,
        special_features=["low_residue", "high_mct"],
        price_per_unit_yuan=130, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220015", brand_name="百普力高能(Peptamen AF)",
        manufacturer="Nestle (雀巢健康科学)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=150,
        protein_source="hydrolysate", protein_content_g_per_100ml=7.6,
        carb_source="麦芽糊精", fat_source="MCT+LCT",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=400,
        special_features=["low_residue", "high_mct"],
        price_per_unit_yuan=145, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220016", brand_name="速愈素(Oral Impact)",
        manufacturer="Nestle (雀巢健康科学)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein+whey", protein_content_g_per_100ml=5.6,
        carb_source="麦芽糊精", fat_source="fish_oil",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=400,
        special_features=["immune_modulation"],
        price_per_unit_yuan=160, unit_size_ml=250,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20220017", brand_name="纽荃星(Infatrini)",
        manufacturer="Nutricia (纽迪希亚)", category="complete",
        target_population="1-10", energy_density_kcal_per_100ml=100,
        protein_source="casein+whey", protein_content_g_per_100ml=2.6,
        carb_source="乳糖+麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=230,
        special_features=[],
        price_per_unit_yuan=90, unit_size_ml=200,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    # Domestic brands
    FSMPProduct(
        nmpa_registration_no="TY20240018", brand_name="基畅(Ener-G)",
        manufacturer="基立福(中国)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=1.5, osmolarity_mOsm_L=260,
        special_features=["fiber_enriched"],
        price_per_unit_yuan=58, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20240019", brand_name="唯源素(Weiyuan Su)",
        manufacturer="亚宝药业", category="complete",
        target_population="1-10", energy_density_kcal_per_100ml=100,
        protein_source="whey", protein_content_g_per_100ml=2.8,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=240,
        special_features=[],
        price_per_unit_yuan=55, unit_size_ml=400,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20240020", brand_name="益力安(Elental)",
        manufacturer="丽珠医药", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="amino_acid", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精", fat_source="MCT",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=290,
        special_features=["elemental", "low_residue", "high_mct"],
        price_per_unit_yuan=160, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),

    # ============ 特定全营养配方 (Specific Complete) ============
    FSMPProduct(
        nmpa_registration_no="TY20230001", brand_name="伊力佳糖尿病(Diben)",
        manufacturer="Nestle (雀巢健康科学)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=100,
        protein_source="casein", protein_content_g_per_100ml=4.3,
        carb_source="果糖+异麦芽酮糖(低GI)", fat_source="mixed(MUFA高)",
        fiber_content_g_per_100ml=1.5, osmolarity_mOsm_L=280,
        special_features=["diabetes"],
        price_per_unit_yuan=110, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230002", brand_name="瑞代糖尿病(Fresubin Diab)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=100,
        protein_source="casein", protein_content_g_per_100ml=4.2,
        carb_source="木薯淀粉+果糖(低GI)", fat_source="MUFA+PUFA",
        fiber_content_g_per_100ml=2.0, osmolarity_mOsm_L=290,
        special_features=["diabetes", "fiber_enriched"],
        price_per_unit_yuan=100, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230003", brand_name="瑞高肾病(Nepro)",
        manufacturer="Abbott (雅培)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=200,
        protein_source="casein", protein_content_g_per_100ml=4.5,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=600,
        special_features=["renal", "high_energy", "low_electrolyte"],
        price_per_unit_yuan=130, unit_size_ml=237,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230004", brand_name="瑞高肾病HP(Nepro HP)",
        manufacturer="Abbott (雅培)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=200,
        protein_source="casein+whey", protein_content_g_per_100ml=8.1,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=680,
        special_features=["renal", "high_energy", "high_protein", "low_electrolyte"],
        price_per_unit_yuan=145, unit_size_ml=237,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230005", brand_name="瑞高肝病(Hepatic Aid)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=100,
        protein_source="amino_acid", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精", fat_source="MCT+LCT",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=350,
        special_features=["hepatic", "high_bcaa", "low_aromatic_aa"],
        price_per_unit_yuan=170, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230006", brand_name="瑞高肝病HP(Hepatic Aid HP)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=130,
        protein_source="amino_acid", protein_content_g_per_100ml=5.0,
        carb_source="麦芽糊精", fat_source="MCT+LCT",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=420,
        special_features=["hepatic", "high_bcaa", "low_aromatic_aa"],
        price_per_unit_yuan=190, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230007", brand_name="瑞能免疫(Supportan Immune)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=100,
        protein_source="casein+whey", protein_content_g_per_100ml=5.6,
        carb_source="麦芽糊精", fat_source="fish_oil+olive_oil",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=310,
        special_features=["immune_modulation", "high_protein"],
        price_per_unit_yuan=150, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230008", brand_name="百普力免疫(Peptamen Immune)",
        manufacturer="Nestle (雀巢健康科学)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=100,
        protein_source="hydrolysate+whey", protein_content_g_per_100ml=5.0,
        carb_source="麦芽糊精", fat_source="fish_oil+olive_oil",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=320,
        special_features=["immune_modulation", "low_residue"],
        price_per_unit_yuan=160, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230009", brand_name="瑞能肿瘤(Supportan Tumor)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=150,
        protein_source="casein+whey", protein_content_g_per_100ml=6.5,
        carb_source="麦芽糊精", fat_source="fish_oil",
        fiber_content_g_per_100ml=1.0, osmolarity_mOsm_L=360,
        special_features=["immune_modulation", "high_protein", "fiber_enriched"],
        price_per_unit_yuan=155, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230010", brand_name="益力佳(Glucerna)",
        manufacturer="Abbott (雅培)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=100,
        protein_source="casein", protein_content_g_per_100ml=4.2,
        carb_source="果糖+麦芽糊精(低GI)", fat_source="MUFA+PUFA",
        fiber_content_g_per_100ml=1.5, osmolarity_mOsm_L=300,
        special_features=["diabetes", "fiber_enriched"],
        price_per_unit_yuan=95, unit_size_ml=400,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230011", brand_name="肺病专用(Pulmocare)",
        manufacturer="Abbott (雅培)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=150,
        protein_source="casein", protein_content_g_per_100ml=5.6,
        carb_source="麦芽糊精(低碳水)", fat_source="mixed(高脂肪)",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=400,
        special_features=["low_carb", "high_fat"],
        price_per_unit_yuan=100, unit_size_ml=237,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230012", brand_name="瑞能伤口愈合(Supportan Wound)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=100,
        protein_source="casein+whey", protein_content_g_per_100ml=6.5,
        carb_source="麦芽糊精", fat_source="fish_oil+olive_oil",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=330,
        special_features=["immune_modulation", "high_protein"],
        price_per_unit_yuan=160, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20230013", brand_name="宜品特爱本佳(PKU)",
        manufacturer="宜品营养", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=100,
        protein_source="amino_acid", protein_content_g_per_100ml=3.5,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=270,
        special_features=["phe_free", "newborn"],
        price_per_unit_yuan=220, unit_size_ml=400,
        hospital_channel="spot_purchase", insurance_coverage=True,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20240014", brand_name="甘亦美流质(Gan Yimei)",
        manufacturer="华森制药", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=100,
        protein_source="casein+whey", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精", fat_source="mixed(极低脂肪)",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=260,
        special_features=["low_fat"],
        price_per_unit_yuan=85, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20240015", brand_name="小唯源素(儿童1-10岁)",
        manufacturer="亚宝药业", category="specific_complete",
        target_population="1-10", energy_density_kcal_per_100ml=100,
        protein_source="whey", protein_content_g_per_100ml=2.8,
        carb_source="麦芽糊精+乳糖", fat_source="mixed",
        fiber_content_g_per_100ml=0.5, osmolarity_mOsm_L=240,
        special_features=["pediatric"],
        price_per_unit_yuan=65, unit_size_ml=400,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    # Domestic specific FSMP
    FSMPProduct(
        nmpa_registration_no="TY20240016", brand_name="松康餐-糖尿病型",
        manufacturer="香颂国际", category="specific_complete",
        target_population="specific_disease", energy_density_kcal_per_100ml=90,
        protein_source="soy+whey", protein_content_g_per_100ml=4.0,
        carb_source="异麦芽酮糖+抗性糊精(低GI)", fat_source="mixed",
        fiber_content_g_per_100ml=2.5, osmolarity_mOsm_L=260,
        special_features=["diabetes", "fiber_enriched"],
        price_per_unit_yuan=50, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),

    # ============ 非全营养配方 (Incomplete) ============
    FSMPProduct(
        nmpa_registration_no="TY20240001", brand_name="瑞素肠内(Fresubin EN Starter)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="incomplete",
        target_population="adult", energy_density_kcal_per_100ml=50,
        protein_source="casein", protein_content_g_per_100ml=2.0,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=180,
        special_features=["low_osmolarity", "starter"],
        price_per_unit_yuan=50, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20240002", brand_name="力存启动(Starter EN)",
        manufacturer="华瑞制药(SSPC)", category="incomplete",
        target_population="adult", energy_density_kcal_per_100ml=50,
        protein_source="casein", protein_content_g_per_100ml=2.0,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=200,
        special_features=["low_osmolarity", "starter"],
        price_per_unit_yuan=45, unit_size_ml=500,
        hospital_channel="tender", insurance_coverage=False,
    ),

    # ============ 组件制剂 (Modular) ============
    FSMPProduct(
        nmpa_registration_no="TY20241001", brand_name="蛋白粉组件(ProMod)",
        manufacturer="Abbott (雅培)", category="modular",
        target_population="adult", energy_density_kcal_per_100ml=30,
        protein_source="whey", protein_content_g_per_100ml=28.0,
        carb_source="none", fat_source="none",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=100,
        special_features=["protein_module"],
        price_per_unit_yuan=120, unit_size_ml=0,  # powder, not liquid
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20241002", brand_name="MCT油组件(MCT Oil)",
        manufacturer="Nutricia (纽迪希亚)", category="modular",
        target_population="adult", energy_density_kcal_per_100ml=850,
        protein_source="none", protein_content_g_per_100ml=0,
        carb_source="none", fat_source="MCT",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=0,
        special_features=["fat_module", "high_mct"],
        price_per_unit_yuan=180, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20241003", brand_name="膳食纤维组件(Benefiber)",
        manufacturer="Nestle (雀巢健康科学)", category="modular",
        target_population="adult", energy_density_kcal_per_100ml=10,
        protein_source="none", protein_content_g_per_100ml=0,
        carb_source="guar_gum", fat_source="none",
        fiber_content_g_per_100ml=100, osmolarity_mOsm_L=50,
        special_features=["fiber_module"],
        price_per_unit_yuan=60, unit_size_ml=0,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20241004", brand_name="谷氨酰胺组件(Glutamine Plus)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="modular",
        target_population="adult", energy_density_kcal_per_100ml=40,
        protein_source="amino_acid", protein_content_g_per_100ml=10.0,
        carb_source="none", fat_source="none",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=200,
        special_features=["glutamine_module", "immune_modulation"],
        price_per_unit_yuan=200, unit_size_ml=0,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20241005", brand_name="精氨酸组件(Arginine Module)",
        manufacturer="Fresenius Kabi (费森尤斯卡比)", category="modular",
        target_population="adult", energy_density_kcal_per_100ml=40,
        protein_source="amino_acid", protein_content_g_per_100ml=10.0,
        carb_source="none", fat_source="none",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=250,
        special_features=["arginine_module", "immune_modulation"],
        price_per_unit_yuan=180, unit_size_ml=0,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),

    # ============ 追加国产品牌全营养 ============
    FSMPProduct(
        nmpa_registration_no="TY20240021", brand_name="佰美乐(Baimeile)",
        manufacturer="南京和美乐生物", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=100,
        protein_source="casein+whey", protein_content_g_per_100ml=4.0,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=1.5, osmolarity_mOsm_L=260,
        special_features=["fiber_enriched"],
        price_per_unit_yuan=52, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20240022", brand_name="基畅高能(Ener-G Plus)",
        manufacturer="基立福(中国)", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=150,
        protein_source="casein", protein_content_g_per_100ml=6.0,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=1.5, osmolarity_mOsm_L=330,
        special_features=["fiber_enriched"],
        price_per_unit_yuan=65, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20240023", brand_name="益力安HP(Elental HP)",
        manufacturer="丽珠医药", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=150,
        protein_source="amino_acid", protein_content_g_per_100ml=6.0,
        carb_source="麦芽糊精", fat_source="MCT",
        fiber_content_g_per_100ml=0, osmolarity_mOsm_L=380,
        special_features=["elemental", "low_residue", "high_mct", "high_protein"],
        price_per_unit_yuan=185, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
    FSMPProduct(
        nmpa_registration_no="TY20240024", brand_name="宜品术后营养(Post-OP)",
        manufacturer="宜品营养", category="complete",
        target_population="adult", energy_density_kcal_per_100ml=130,
        protein_source="whey+casein", protein_content_g_per_100ml=5.5,
        carb_source="麦芽糊精", fat_source="mixed",
        fiber_content_g_per_100ml=1.0, osmolarity_mOsm_L=310,
        special_features=["fiber_enriched"],
        price_per_unit_yuan=68, unit_size_ml=500,
        hospital_channel="spot_purchase", insurance_coverage=False,
    ),
]


def get_mvp_products() -> list[FSMPProduct]:
    return MVP_FSMP_PRODUCTS
